name: Cypress
on:
  pull_request:
    branches: [develop, master]

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        echo "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID_TEST }}" >> .env
        echo "CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN_TEST }}" >> .env
        echo "CONTENTFUL_ENVIRONMENT_ID=develop" >> .env
        echo "BACKEND_AUTH_KEY=hemmelig" >> .env
        echo "ADMIN_KEY=hemmelig" >> .env

    - name: Run Cypress end-to-end tests with Docker Compose
      run: yarn e2e
