name: Cypress
on:
  pull_request:
    branches: [develop, master]

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout frontend repository
      uses: actions/checkout@v2

    - name: Checkout backend repository
      uses: actions/checkout@v2
      with:
        repository: echo-webkom/echo-web-backend
        path: backend
        ref: master

    - name: Set up environment
      run: |
        echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" >> .env
        echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> .env
        echo "CONTENTFUL_ENVIRONMENT_ID=$CONTENTFUL_ENVIRONMENT_ID" >> .env
        echo "BEDKOM_KEY=$BEDKOM_KEY" >> .env
      env:
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID_TEST }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN_TEST }}
        CONTENTFUL_ENVIRONMENT_ID: develop
        BEDKOM_KEY: bedkom-passord

    - name: Set up Docker images
      run: |
        docker-compose -f backend/docker-compose.yaml pull
        docker-compose -f backend/docker-compose.yaml build

    - name: Install dependencies and build
      run: |
        yarn --frozen-lockfile
        yarn build

    - name: Run Cypress end-to-end tests
      run: |
        yarn start &
        docker-compose -f backend/docker-compose.yaml up &
        yarn wait-on --interval 1000 http-get://localhost:3000
        yarn wait-on --interval 1000 http-get://localhost:8080/status
        sh backend/test_scripts/submit_bedpres -t -x $WEBKOM_KEY || exit 1
        yarn cypress run --config video=false,screenshotOnRunFailure=false
      env:
        WEBKOM_KEY: webkom-passord
