name: Edit weekly PR on develop push
on:
  pull_request:
    branches: master
    types: synchronize

jobs:
  edit_release:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: develop
          # Needed for git log history
          fetch-depth: 0

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install -yq --no-install-recommends gh

      - name: Edit pull request
        run: |
          gh config set prompt disabled
          COMMITS=$(git log origin/master..origin/develop --no-merges --reverse --format=format:%h\ %s\<br\>\<br\>)
          gh pr edit \
            -b "<h1>Weekly release</h1><h2>Commits since last release</h2><b>$COMMITS</b>" \
            develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
